<a href="https://colab.research.google.com/github/TheRadDani/Pytorch-exercises/blob/main/einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch

import numpy as np

a = np.random.rand(5)
b = np.random.rand(3)
np.einsum('i,j->ij',a,b) #outer product

array([[0.2316721 , 0.10868752, 0.21707048],
       [0.00509478, 0.00239018, 0.00477367],
       [0.08723339, 0.040925  , 0.08173533],
       [0.24086704, 0.11300127, 0.22568589],
       [0.26708643, 0.12530194, 0.25025275]])

In [9]:
#omitting a letter means that axis wil be summed
x = np.ones(3)
np.einsum('i->',x)

3.0

In [11]:
x = np.ones((5,4,3))
print(x.shape)
new_x = np.einsum('ijk->kji',x)
print(new_x.shape)

(5, 4, 3)
(3, 4, 5)


In [55]:
x = torch.rand((2,3))
print("x val:\n",x)
print("dimensions",x.shape)
#permutation of tensors
a = torch.einsum('ij->ji',x)
print("permutation dimensions",a.shape)
#summation
sum = torch.einsum('ij->',x)
print("x sum:",sum)

#column sum
col_sum = torch.einsum("ij->j",x)
print("col_sum",col_sum)

#row_sum
row_sum = torch.einsum("ij->i",x)
print("row_sum",row_sum)

#Matrix-vector multiplication
v = torch.rand((1,3))
mv_mult = torch.einsum("ij,kj->ik",x,v)
print("mv_mult:\n",mv_mult)


#Matrix-Matrix Multiplication
mm_mult = torch.einsum("ij,kj->ik",x,x)
print("mm_mult:\n",mm_mult)

#dot product first row with first row of matrix
dot_prod_row_one = torch.einsum("i,i->",x[0],x[0])
print("dot_prod_row_one:\n",dot_prod_row_one)

#dot product with matrix
dot_product_matrix = torch.einsum('ij,ij->',x,x)
print("dot_product_matrix:\n",dot_product_matrix)

#hadamard product (element-wise multiplication)
hadamard = torch.einsum('ij,ij->ij',x,x)
print("hadamard:\n",hadamard)

#outer product
outer_product = torch.einsum('i,j->ij',x[0],x[1])
print("outer product:\n",outer_product)

#batch matrix multiplication
a = torch.rand((3,2,5))
print("a:\n",a)
b = torch.rand((3,5,3))
print("b:\n",b)
batch = torch.einsum('ijk,ikl->ijl',a,b)
print("batch:\n",batch)


#matrix Diagonal
x = torch.rand((3,3))
print("x:\n",x)
diagonal = torch.einsum("ii->i",x)
print("diagonal:\n",diagonal)

#matrix trace
trace = torch.einsum("ii->",x)
print("trace:\n",trace)

x val:
 tensor([[0.2744, 0.4309, 0.1928],
        [0.2639, 0.7192, 0.9685]])
dimensions torch.Size([2, 3])
permutation dimensions torch.Size([3, 2])
x sum: tensor(2.8497)
col_sum tensor([0.5384, 1.1500, 1.1613])
row_sum tensor([0.8980, 1.9517])
mv_mult:
 tensor([[0.4062],
        [0.6974]])
mm_mult:
 tensor([[0.2981, 0.5690],
        [0.5690, 1.5250]])
dot_prod_row_one:
 tensor(0.2981)
dot_product_matrix:
 tensor(1.8230)
hadamard:
 tensor([[0.0753, 0.1856, 0.0372],
        [0.0697, 0.5172, 0.9381]])
outer product:
 tensor([[0.0724, 0.1974, 0.2658],
        [0.1137, 0.3099, 0.4173],
        [0.0509, 0.1386, 0.1867]])
a:
 tensor([[[0.5187, 0.2216, 0.1134, 0.2009, 0.8906],
         [0.1932, 0.6920, 0.0114, 0.2966, 0.1341]],

        [[0.3856, 0.2382, 0.8371, 0.9068, 0.1827],
         [0.9702, 0.4751, 0.0105, 0.9040, 0.9272]],

        [[0.7795, 0.4208, 0.9007, 0.6667, 0.5053],
         [0.0148, 0.5597, 0.7690, 0.0461, 0.8731]]])
b:
 tensor([[[0.6405, 0.6019, 0.0588],
         [0.8799, 0.7